package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String adminFirstName;
	private String adminMiddleName;
	private String adminLastName;
	private String adminSecurityQues;
	private String adminSecurityAnswer;
	private String adminEmailId;
	private String adminPassword;
	private String adminRepassword;
	private String adminPhoto;
	private byte[] adminHscanFile;
	private Integer adminVid;
	private Integer adminCanRegId;
	private String adminStatus;
	private String adminVstatus1;
	private String adminCanStatus1;
	private Set voterregistrations = new HashSet(0);
	private Set castvotes = new HashSet(0);
	private Set candidateregistrations = new HashSet(0);
	private Set trackapplications = new HashSet(0);

	public Admin() {
	}

	public Admin(String adminFirstName, String adminMiddleName, String adminLastName, String adminSecurityQues,
			String adminSecurityAnswer, String adminEmailId, String adminPassword, String adminRepassword,
			String adminPhoto, byte[] adminHscanFile, Integer adminVid, Integer adminCanRegId, String adminStatus,
			String adminVstatus1, String adminCanStatus1, Set voterregistrations, Set castvotes,
			Set candidateregistrations, Set trackapplications) {
		this.adminFirstName = adminFirstName;
		this.adminMiddleName = adminMiddleName;
		this.adminLastName = adminLastName;
		this.adminSecurityQues = adminSecurityQues;
		this.adminSecurityAnswer = adminSecurityAnswer;
		this.adminEmailId = adminEmailId;
		this.adminPassword = adminPassword;
		this.adminRepassword = adminRepassword;
		this.adminPhoto = adminPhoto;
		this.adminHscanFile = adminHscanFile;
		this.adminVid = adminVid;
		this.adminCanRegId = adminCanRegId;
		this.adminStatus = adminStatus;
		this.adminVstatus1 = adminVstatus1;
		this.adminCanStatus1 = adminCanStatus1;
		this.voterregistrations = voterregistrations;
		this.castvotes = castvotes;
		this.candidateregistrations = candidateregistrations;
		this.trackapplications = trackapplications;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminFirstName() {
		return this.adminFirstName;
	}

	public void setAdminFirstName(String adminFirstName) {
		this.adminFirstName = adminFirstName;
	}

	public String getAdminMiddleName() {
		return this.adminMiddleName;
	}

	public void setAdminMiddleName(String adminMiddleName) {
		this.adminMiddleName = adminMiddleName;
	}

	public String getAdminLastName() {
		return this.adminLastName;
	}

	public void setAdminLastName(String adminLastName) {
		this.adminLastName = adminLastName;
	}

	public String getAdminSecurityQues() {
		return this.adminSecurityQues;
	}

	public void setAdminSecurityQues(String adminSecurityQues) {
		this.adminSecurityQues = adminSecurityQues;
	}

	public String getAdminSecurityAnswer() {
		return this.adminSecurityAnswer;
	}

	public void setAdminSecurityAnswer(String adminSecurityAnswer) {
		this.adminSecurityAnswer = adminSecurityAnswer;
	}

	public String getAdminEmailId() {
		return this.adminEmailId;
	}

	public void setAdminEmailId(String adminEmailId) {
		this.adminEmailId = adminEmailId;
	}

	public String getAdminPassword() {
		return this.adminPassword;
	}

	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	public String getAdminRepassword() {
		return this.adminRepassword;
	}

	public void setAdminRepassword(String adminRepassword) {
		this.adminRepassword = adminRepassword;
	}

	public String getAdminPhoto() {
		return this.adminPhoto;
	}

	public void setAdminPhoto(String adminPhoto) {
		this.adminPhoto = adminPhoto;
	}

	public byte[] getAdminHscanFile() {
		return this.adminHscanFile;
	}

	public void setAdminHscanFile(byte[] adminHscanFile) {
		this.adminHscanFile = adminHscanFile;
	}

	public Integer getAdminVid() {
		return this.adminVid;
	}

	public void setAdminVid(Integer adminVid) {
		this.adminVid = adminVid;
	}

	public Integer getAdminCanRegId() {
		return this.adminCanRegId;
	}

	public void setAdminCanRegId(Integer adminCanRegId) {
		this.adminCanRegId = adminCanRegId;
	}

	public String getAdminStatus() {
		return this.adminStatus;
	}

	public void setAdminStatus(String adminStatus) {
		this.adminStatus = adminStatus;
	}

	public String getAdminVstatus1() {
		return this.adminVstatus1;
	}

	public void setAdminVstatus1(String adminVstatus1) {
		this.adminVstatus1 = adminVstatus1;
	}

	public String getAdminCanStatus1() {
		return this.adminCanStatus1;
	}

	public void setAdminCanStatus1(String adminCanStatus1) {
		this.adminCanStatus1 = adminCanStatus1;
	}

	public Set getVoterregistrations() {
		return this.voterregistrations;
	}

	public void setVoterregistrations(Set voterregistrations) {
		this.voterregistrations = voterregistrations;
	}

	public Set getCastvotes() {
		return this.castvotes;
	}

	public void setCastvotes(Set castvotes) {
		this.castvotes = castvotes;
	}

	public Set getCandidateregistrations() {
		return this.candidateregistrations;
	}

	public void setCandidateregistrations(Set candidateregistrations) {
		this.candidateregistrations = candidateregistrations;
	}

	public Set getTrackapplications() {
		return this.trackapplications;
	}

	public void setTrackapplications(Set trackapplications) {
		this.trackapplications = trackapplications;
	}

}
