package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Bjp generated by hbm2java
 */
public class Bjp implements java.io.Serializable {

	private Integer bjpId;
	private String bjpName;
	private Integer bjpCandidateRegId;
	private Integer bjpTotalVotes;
	private Integer bjpStateTotalVotes;
	private Integer bjpCityTotalVotes;
	private Integer bjpAreaTotalVotes;
	private Integer bjpFemaleTotalVotes;
	private Integer bjpMaleTotalVotes;

	public Bjp() {
	}

	public Bjp(String bjpName, Integer bjpCandidateRegId, Integer bjpTotalVotes, Integer bjpStateTotalVotes,
			Integer bjpCityTotalVotes, Integer bjpAreaTotalVotes, Integer bjpFemaleTotalVotes, Integer bjpMaleTotalVotes) {
		this.bjpName = bjpName;
		this.bjpCandidateRegId = bjpCandidateRegId;
		this.bjpTotalVotes = bjpTotalVotes;
		this.bjpStateTotalVotes = bjpStateTotalVotes;
		this.bjpCityTotalVotes = bjpCityTotalVotes;
		this.bjpAreaTotalVotes = bjpAreaTotalVotes;
		this.bjpFemaleTotalVotes = bjpFemaleTotalVotes;
		this.bjpMaleTotalVotes = bjpMaleTotalVotes;
	}

	public Integer getBjpId() {
		return this.bjpId;
	}

	public void setBjpId(Integer bjpId) {
		this.bjpId = bjpId;
	}

	public String getBjpName() {
		return this.bjpName;
	}

	public void setBjpName(String bjpName) {
		this.bjpName = bjpName;
	}

	public Integer getBjpCandidateRegId() {
		return this.bjpCandidateRegId;
	}

	public void setBjpCandidateRegId(Integer bjpCandidateRegId) {
		this.bjpCandidateRegId = bjpCandidateRegId;
	}

	public Integer getBjpTotalVotes() {
		return this.bjpTotalVotes;
	}

	public void setBjpTotalVotes(Integer bjpTotalVotes) {
		this.bjpTotalVotes = bjpTotalVotes;
	}

	public Integer getBjpStateTotalVotes() {
		return this.bjpStateTotalVotes;
	}

	public void setBjpStateTotalVotes(Integer bjpStateTotalVotes) {
		this.bjpStateTotalVotes = bjpStateTotalVotes;
	}

	public Integer getBjpCityTotalVotes() {
		return this.bjpCityTotalVotes;
	}

	public void setBjpCityTotalVotes(Integer bjpCityTotalVotes) {
		this.bjpCityTotalVotes = bjpCityTotalVotes;
	}

	public Integer getBjpAreaTotalVotes() {
		return this.bjpAreaTotalVotes;
	}

	public void setBjpAreaTotalVotes(Integer bjpAreaTotalVotes) {
		this.bjpAreaTotalVotes = bjpAreaTotalVotes;
	}

	public Integer getBjpFemaleTotalVotes() {
		return this.bjpFemaleTotalVotes;
	}

	public void setBjpFemaleTotalVotes(Integer bjpFemaleTotalVotes) {
		this.bjpFemaleTotalVotes = bjpFemaleTotalVotes;
	}

	public Integer getBjpMaleTotalVotes() {
		return this.bjpMaleTotalVotes;
	}

	public void setBjpMaleTotalVotes(Integer bjpMaleTotalVotes) {
		this.bjpMaleTotalVotes = bjpMaleTotalVotes;
	}

}
