package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Candidateregistration generated by hbm2java
 */
public class Candidateregistration implements java.io.Serializable {

	private Integer canId;
	private Party party;
	private Admin admin;
	private String canfirstname;
	private String canmiddlename;
	private String canlastname;
	private String cangender;
	private String canmaritalstatus;
	private String canfathername;
	private String canmothername;
	private String canwifename;
	private String canhusbandname;
	private String cangaurdianname;
	private Integer canage;
	private Date candob;
	private String canpermacountry;
	private String canpermastate;
	private String canpermacity;
	private String canpermatown;
	private String canpermaaddress;
	private String canpermapincode;
	private String cancorrescountry;
	private String cancorresstate;
	private String cancorrescity;
	private String cancorrestown;
	private String cancorresaddress;
	private String cancorrespincode;
	private String canoccupationstatus;
	private byte[] canoccupationdoc;
	private String candesignation;
	private String canadharno;
	private byte[] canadhardoc;
	private String canpanno;
	private byte[] canpandoc;
	private String canphoto;
	private String canmob;
	private Integer canAddressId;
	private Boolean canpwdstatus;
	private String canpwdudidno;
	private byte[] canpwddoc;
	private String canPartyName;
	private String canNomiAreaCountry;
	private String canNomiAreaState;
	private String canNomiAreaCity;
	private String canNomiAreaTown;
	private String canNomiAreaPincode;
	private String canEmailId;
	private String canPassword;
	private String canRepassword;
	private String canSecurityQues;
	private String canSecurityAnswer;
	private String canNominationId;
	private Boolean canCreditStatus;
	private String canCreditRelation;
	private String canCreditName;
	private Integer canCreditPartyId;
	private String canCreditPartyName;
	private String canCreditDesignation;
	private Boolean canCriminalStatus;
	private String canCriminalRecord;
	private byte[] canCriminalDoc;
	private String canCancelRegistration;
	private String canCancelOtherDetails;
	private byte[] canCancelRegistrationDoc;
	private Integer canCastId;
	private String canStatus1;
	private String canStatus2;
	private String canStatus3;
	private Integer canBspId;
	private Integer canBjpId;
	private Integer canNcpId;
	private Integer canIncpId;
	private Integer canCpiId;
	private Integer canTotalVotes;
	private Set castvotes = new HashSet(0);
	private Set addresses = new HashSet(0);

	public Candidateregistration() {
	}

	public Candidateregistration(Party party, Admin admin, String canfirstname, String canmiddlename,
			String canlastname, String cangender, String canmaritalstatus, String canfathername, String canmothername,
			String canwifename, String canhusbandname, String cangaurdianname, Integer canage, Date candob,
			String canpermacountry, String canpermastate, String canpermacity, String canpermatown,
			String canpermaaddress, String canpermapincode, String cancorrescountry, String cancorresstate,
			String cancorrescity, String cancorrestown, String cancorresaddress, String cancorrespincode,
			String canoccupationstatus, byte[] canoccupationdoc, String candesignation, String canadharno,
			byte[] canadhardoc, String canpanno, byte[] canpandoc, String canphoto, String canmob,
			Integer canAddressId, Boolean canpwdstatus, String canpwdudidno, byte[] canpwddoc, String canPartyName,
			String canNomiAreaCountry, String canNomiAreaState, String canNomiAreaCity, String canNomiAreaTown,
			String canNomiAreaPincode, String canEmailId, String canPassword, String canRepassword,
			String canSecurityQues, String canSecurityAnswer, String canNominationId, Boolean canCreditStatus,
			String canCreditRelation, String canCreditName, Integer canCreditPartyId, String canCreditPartyName,
			String canCreditDesignation, Boolean canCriminalStatus, String canCriminalRecord, byte[] canCriminalDoc,
			String canCancelRegistration, String canCancelOtherDetails, byte[] canCancelRegistrationDoc,
			Integer canCastId, String canStatus1, String canStatus2, String canStatus3, Integer canBspId,
			Integer canBjpId, Integer canNcpId, Integer canIncpId, Integer canCpiId, Integer canTotalVotes,
			Set castvotes, Set addresses) {
		this.party = party;
		this.admin = admin;
		this.canfirstname = canfirstname;
		this.canmiddlename = canmiddlename;
		this.canlastname = canlastname;
		this.cangender = cangender;
		this.canmaritalstatus = canmaritalstatus;
		this.canfathername = canfathername;
		this.canmothername = canmothername;
		this.canwifename = canwifename;
		this.canhusbandname = canhusbandname;
		this.cangaurdianname = cangaurdianname;
		this.canage = canage;
		this.candob = candob;
		this.canpermacountry = canpermacountry;
		this.canpermastate = canpermastate;
		this.canpermacity = canpermacity;
		this.canpermatown = canpermatown;
		this.canpermaaddress = canpermaaddress;
		this.canpermapincode = canpermapincode;
		this.cancorrescountry = cancorrescountry;
		this.cancorresstate = cancorresstate;
		this.cancorrescity = cancorrescity;
		this.cancorrestown = cancorrestown;
		this.cancorresaddress = cancorresaddress;
		this.cancorrespincode = cancorrespincode;
		this.canoccupationstatus = canoccupationstatus;
		this.canoccupationdoc = canoccupationdoc;
		this.candesignation = candesignation;
		this.canadharno = canadharno;
		this.canadhardoc = canadhardoc;
		this.canpanno = canpanno;
		this.canpandoc = canpandoc;
		this.canphoto = canphoto;
		this.canmob = canmob;
		this.canAddressId = canAddressId;
		this.canpwdstatus = canpwdstatus;
		this.canpwdudidno = canpwdudidno;
		this.canpwddoc = canpwddoc;
		this.canPartyName = canPartyName;
		this.canNomiAreaCountry = canNomiAreaCountry;
		this.canNomiAreaState = canNomiAreaState;
		this.canNomiAreaCity = canNomiAreaCity;
		this.canNomiAreaTown = canNomiAreaTown;
		this.canNomiAreaPincode = canNomiAreaPincode;
		this.canEmailId = canEmailId;
		this.canPassword = canPassword;
		this.canRepassword = canRepassword;
		this.canSecurityQues = canSecurityQues;
		this.canSecurityAnswer = canSecurityAnswer;
		this.canNominationId = canNominationId;
		this.canCreditStatus = canCreditStatus;
		this.canCreditRelation = canCreditRelation;
		this.canCreditName = canCreditName;
		this.canCreditPartyId = canCreditPartyId;
		this.canCreditPartyName = canCreditPartyName;
		this.canCreditDesignation = canCreditDesignation;
		this.canCriminalStatus = canCriminalStatus;
		this.canCriminalRecord = canCriminalRecord;
		this.canCriminalDoc = canCriminalDoc;
		this.canCancelRegistration = canCancelRegistration;
		this.canCancelOtherDetails = canCancelOtherDetails;
		this.canCancelRegistrationDoc = canCancelRegistrationDoc;
		this.canCastId = canCastId;
		this.canStatus1 = canStatus1;
		this.canStatus2 = canStatus2;
		this.canStatus3 = canStatus3;
		this.canBspId = canBspId;
		this.canBjpId = canBjpId;
		this.canNcpId = canNcpId;
		this.canIncpId = canIncpId;
		this.canCpiId = canCpiId;
		this.canTotalVotes = canTotalVotes;
		this.castvotes = castvotes;
		this.addresses = addresses;
	}

	public Integer getCanId() {
		return this.canId;
	}

	public void setCanId(Integer canId) {
		this.canId = canId;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getCanfirstname() {
		return this.canfirstname;
	}

	public void setCanfirstname(String canfirstname) {
		this.canfirstname = canfirstname;
	}

	public String getCanmiddlename() {
		return this.canmiddlename;
	}

	public void setCanmiddlename(String canmiddlename) {
		this.canmiddlename = canmiddlename;
	}

	public String getCanlastname() {
		return this.canlastname;
	}

	public void setCanlastname(String canlastname) {
		this.canlastname = canlastname;
	}

	public String getCangender() {
		return this.cangender;
	}

	public void setCangender(String cangender) {
		this.cangender = cangender;
	}

	public String getCanmaritalstatus() {
		return this.canmaritalstatus;
	}

	public void setCanmaritalstatus(String canmaritalstatus) {
		this.canmaritalstatus = canmaritalstatus;
	}

	public String getCanfathername() {
		return this.canfathername;
	}

	public void setCanfathername(String canfathername) {
		this.canfathername = canfathername;
	}

	public String getCanmothername() {
		return this.canmothername;
	}

	public void setCanmothername(String canmothername) {
		this.canmothername = canmothername;
	}

	public String getCanwifename() {
		return this.canwifename;
	}

	public void setCanwifename(String canwifename) {
		this.canwifename = canwifename;
	}

	public String getCanhusbandname() {
		return this.canhusbandname;
	}

	public void setCanhusbandname(String canhusbandname) {
		this.canhusbandname = canhusbandname;
	}

	public String getCangaurdianname() {
		return this.cangaurdianname;
	}

	public void setCangaurdianname(String cangaurdianname) {
		this.cangaurdianname = cangaurdianname;
	}

	public Integer getCanage() {
		return this.canage;
	}

	public void setCanage(Integer canage) {
		this.canage = canage;
	}

	public Date getCandob() {
		return this.candob;
	}

	public void setCandob(Date candob) {
		this.candob = candob;
	}

	public String getCanpermacountry() {
		return this.canpermacountry;
	}

	public void setCanpermacountry(String canpermacountry) {
		this.canpermacountry = canpermacountry;
	}

	public String getCanpermastate() {
		return this.canpermastate;
	}

	public void setCanpermastate(String canpermastate) {
		this.canpermastate = canpermastate;
	}

	public String getCanpermacity() {
		return this.canpermacity;
	}

	public void setCanpermacity(String canpermacity) {
		this.canpermacity = canpermacity;
	}

	public String getCanpermatown() {
		return this.canpermatown;
	}

	public void setCanpermatown(String canpermatown) {
		this.canpermatown = canpermatown;
	}

	public String getCanpermaaddress() {
		return this.canpermaaddress;
	}

	public void setCanpermaaddress(String canpermaaddress) {
		this.canpermaaddress = canpermaaddress;
	}

	public String getCanpermapincode() {
		return this.canpermapincode;
	}

	public void setCanpermapincode(String canpermapincode) {
		this.canpermapincode = canpermapincode;
	}

	public String getCancorrescountry() {
		return this.cancorrescountry;
	}

	public void setCancorrescountry(String cancorrescountry) {
		this.cancorrescountry = cancorrescountry;
	}

	public String getCancorresstate() {
		return this.cancorresstate;
	}

	public void setCancorresstate(String cancorresstate) {
		this.cancorresstate = cancorresstate;
	}

	public String getCancorrescity() {
		return this.cancorrescity;
	}

	public void setCancorrescity(String cancorrescity) {
		this.cancorrescity = cancorrescity;
	}

	public String getCancorrestown() {
		return this.cancorrestown;
	}

	public void setCancorrestown(String cancorrestown) {
		this.cancorrestown = cancorrestown;
	}

	public String getCancorresaddress() {
		return this.cancorresaddress;
	}

	public void setCancorresaddress(String cancorresaddress) {
		this.cancorresaddress = cancorresaddress;
	}

	public String getCancorrespincode() {
		return this.cancorrespincode;
	}

	public void setCancorrespincode(String cancorrespincode) {
		this.cancorrespincode = cancorrespincode;
	}

	public String getCanoccupationstatus() {
		return this.canoccupationstatus;
	}

	public void setCanoccupationstatus(String canoccupationstatus) {
		this.canoccupationstatus = canoccupationstatus;
	}

	public byte[] getCanoccupationdoc() {
		return this.canoccupationdoc;
	}

	public void setCanoccupationdoc(byte[] canoccupationdoc) {
		this.canoccupationdoc = canoccupationdoc;
	}

	public String getCandesignation() {
		return this.candesignation;
	}

	public void setCandesignation(String candesignation) {
		this.candesignation = candesignation;
	}

	public String getCanadharno() {
		return this.canadharno;
	}

	public void setCanadharno(String canadharno) {
		this.canadharno = canadharno;
	}

	public byte[] getCanadhardoc() {
		return this.canadhardoc;
	}

	public void setCanadhardoc(byte[] canadhardoc) {
		this.canadhardoc = canadhardoc;
	}

	public String getCanpanno() {
		return this.canpanno;
	}

	public void setCanpanno(String canpanno) {
		this.canpanno = canpanno;
	}

	public byte[] getCanpandoc() {
		return this.canpandoc;
	}

	public void setCanpandoc(byte[] canpandoc) {
		this.canpandoc = canpandoc;
	}

	public String getCanphoto() {
		return this.canphoto;
	}

	public void setCanphoto(String canphoto) {
		this.canphoto = canphoto;
	}

	public String getCanmob() {
		return this.canmob;
	}

	public void setCanmob(String canmob) {
		this.canmob = canmob;
	}

	public Integer getCanAddressId() {
		return this.canAddressId;
	}

	public void setCanAddressId(Integer canAddressId) {
		this.canAddressId = canAddressId;
	}

	public Boolean getCanpwdstatus() {
		return this.canpwdstatus;
	}

	public void setCanpwdstatus(Boolean canpwdstatus) {
		this.canpwdstatus = canpwdstatus;
	}

	public String getCanpwdudidno() {
		return this.canpwdudidno;
	}

	public void setCanpwdudidno(String canpwdudidno) {
		this.canpwdudidno = canpwdudidno;
	}

	public byte[] getCanpwddoc() {
		return this.canpwddoc;
	}

	public void setCanpwddoc(byte[] canpwddoc) {
		this.canpwddoc = canpwddoc;
	}

	public String getCanPartyName() {
		return this.canPartyName;
	}

	public void setCanPartyName(String canPartyName) {
		this.canPartyName = canPartyName;
	}

	public String getCanNomiAreaCountry() {
		return this.canNomiAreaCountry;
	}

	public void setCanNomiAreaCountry(String canNomiAreaCountry) {
		this.canNomiAreaCountry = canNomiAreaCountry;
	}

	public String getCanNomiAreaState() {
		return this.canNomiAreaState;
	}

	public void setCanNomiAreaState(String canNomiAreaState) {
		this.canNomiAreaState = canNomiAreaState;
	}

	public String getCanNomiAreaCity() {
		return this.canNomiAreaCity;
	}

	public void setCanNomiAreaCity(String canNomiAreaCity) {
		this.canNomiAreaCity = canNomiAreaCity;
	}

	public String getCanNomiAreaTown() {
		return this.canNomiAreaTown;
	}

	public void setCanNomiAreaTown(String canNomiAreaTown) {
		this.canNomiAreaTown = canNomiAreaTown;
	}

	public String getCanNomiAreaPincode() {
		return this.canNomiAreaPincode;
	}

	public void setCanNomiAreaPincode(String canNomiAreaPincode) {
		this.canNomiAreaPincode = canNomiAreaPincode;
	}

	public String getCanEmailId() {
		return this.canEmailId;
	}

	public void setCanEmailId(String canEmailId) {
		this.canEmailId = canEmailId;
	}

	public String getCanPassword() {
		return this.canPassword;
	}

	public void setCanPassword(String canPassword) {
		this.canPassword = canPassword;
	}

	public String getCanRepassword() {
		return this.canRepassword;
	}

	public void setCanRepassword(String canRepassword) {
		this.canRepassword = canRepassword;
	}

	public String getCanSecurityQues() {
		return this.canSecurityQues;
	}

	public void setCanSecurityQues(String canSecurityQues) {
		this.canSecurityQues = canSecurityQues;
	}

	public String getCanSecurityAnswer() {
		return this.canSecurityAnswer;
	}

	public void setCanSecurityAnswer(String canSecurityAnswer) {
		this.canSecurityAnswer = canSecurityAnswer;
	}

	public String getCanNominationId() {
		return this.canNominationId;
	}

	public void setCanNominationId(String canNominationId) {
		this.canNominationId = canNominationId;
	}

	public Boolean getCanCreditStatus() {
		return this.canCreditStatus;
	}

	public void setCanCreditStatus(Boolean canCreditStatus) {
		this.canCreditStatus = canCreditStatus;
	}

	public String getCanCreditRelation() {
		return this.canCreditRelation;
	}

	public void setCanCreditRelation(String canCreditRelation) {
		this.canCreditRelation = canCreditRelation;
	}

	public String getCanCreditName() {
		return this.canCreditName;
	}

	public void setCanCreditName(String canCreditName) {
		this.canCreditName = canCreditName;
	}

	public Integer getCanCreditPartyId() {
		return this.canCreditPartyId;
	}

	public void setCanCreditPartyId(Integer canCreditPartyId) {
		this.canCreditPartyId = canCreditPartyId;
	}

	public String getCanCreditPartyName() {
		return this.canCreditPartyName;
	}

	public void setCanCreditPartyName(String canCreditPartyName) {
		this.canCreditPartyName = canCreditPartyName;
	}

	public String getCanCreditDesignation() {
		return this.canCreditDesignation;
	}

	public void setCanCreditDesignation(String canCreditDesignation) {
		this.canCreditDesignation = canCreditDesignation;
	}

	public Boolean getCanCriminalStatus() {
		return this.canCriminalStatus;
	}

	public void setCanCriminalStatus(Boolean canCriminalStatus) {
		this.canCriminalStatus = canCriminalStatus;
	}

	public String getCanCriminalRecord() {
		return this.canCriminalRecord;
	}

	public void setCanCriminalRecord(String canCriminalRecord) {
		this.canCriminalRecord = canCriminalRecord;
	}

	public byte[] getCanCriminalDoc() {
		return this.canCriminalDoc;
	}

	public void setCanCriminalDoc(byte[] canCriminalDoc) {
		this.canCriminalDoc = canCriminalDoc;
	}

	public String getCanCancelRegistration() {
		return this.canCancelRegistration;
	}

	public void setCanCancelRegistration(String canCancelRegistration) {
		this.canCancelRegistration = canCancelRegistration;
	}

	public String getCanCancelOtherDetails() {
		return this.canCancelOtherDetails;
	}

	public void setCanCancelOtherDetails(String canCancelOtherDetails) {
		this.canCancelOtherDetails = canCancelOtherDetails;
	}

	public byte[] getCanCancelRegistrationDoc() {
		return this.canCancelRegistrationDoc;
	}

	public void setCanCancelRegistrationDoc(byte[] canCancelRegistrationDoc) {
		this.canCancelRegistrationDoc = canCancelRegistrationDoc;
	}

	public Integer getCanCastId() {
		return this.canCastId;
	}

	public void setCanCastId(Integer canCastId) {
		this.canCastId = canCastId;
	}

	public String getCanStatus1() {
		return this.canStatus1;
	}

	public void setCanStatus1(String canStatus1) {
		this.canStatus1 = canStatus1;
	}

	public String getCanStatus2() {
		return this.canStatus2;
	}

	public void setCanStatus2(String canStatus2) {
		this.canStatus2 = canStatus2;
	}

	public String getCanStatus3() {
		return this.canStatus3;
	}

	public void setCanStatus3(String canStatus3) {
		this.canStatus3 = canStatus3;
	}

	public Integer getCanBspId() {
		return this.canBspId;
	}

	public void setCanBspId(Integer canBspId) {
		this.canBspId = canBspId;
	}

	public Integer getCanBjpId() {
		return this.canBjpId;
	}

	public void setCanBjpId(Integer canBjpId) {
		this.canBjpId = canBjpId;
	}

	public Integer getCanNcpId() {
		return this.canNcpId;
	}

	public void setCanNcpId(Integer canNcpId) {
		this.canNcpId = canNcpId;
	}

	public Integer getCanIncpId() {
		return this.canIncpId;
	}

	public void setCanIncpId(Integer canIncpId) {
		this.canIncpId = canIncpId;
	}

	public Integer getCanCpiId() {
		return this.canCpiId;
	}

	public void setCanCpiId(Integer canCpiId) {
		this.canCpiId = canCpiId;
	}

	public Integer getCanTotalVotes() {
		return this.canTotalVotes;
	}

	public void setCanTotalVotes(Integer canTotalVotes) {
		this.canTotalVotes = canTotalVotes;
	}

	public Set getCastvotes() {
		return this.castvotes;
	}

	public void setCastvotes(Set castvotes) {
		this.castvotes = castvotes;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
