package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Castvote generated by hbm2java
 */
public class Castvote implements java.io.Serializable {

	private Integer castId;
	private Admin admin;
	private Candidateregistration candidateregistration;
	private Party party;
	private String castVfirstName;
	private String castVlastName;
	private Integer castVid;
	private String castEpicNo;
	private String castVadharNo;
	private String castVpanNo;
	private String castVsecurtiyQues;
	private String castVsecurityAnsw;
	private String castVpassword;
	private String castVotingCountry;
	private String castVotingState;
	private String castVotingCity;
	private String castVotingTown;
	private String castVotingPincode;
	private String castVotingPartyName;
	private Integer castCanId;
	private String castCanName;
	private byte[] castCanSymbol;
	private Date castVoteTime;
	private String castVotingStatus;
	private Set voterregistrations = new HashSet(0);
	private Set resultprocesses = new HashSet(0);

	public Castvote() {
	}

	public Castvote(Admin admin, Candidateregistration candidateregistration, Party party, String castVfirstName,
			String castVlastName, Integer castVid, String castEpicNo, String castVadharNo, String castVpanNo,
			String castVsecurtiyQues, String castVsecurityAnsw, String castVpassword, String castVotingCountry,
			String castVotingState, String castVotingCity, String castVotingTown, String castVotingPincode,
			String castVotingPartyName, Integer castCanId, String castCanName, byte[] castCanSymbol, Date castVoteTime,
			String castVotingStatus, Set voterregistrations, Set resultprocesses) {
		this.admin = admin;
		this.candidateregistration = candidateregistration;
		this.party = party;
		this.castVfirstName = castVfirstName;
		this.castVlastName = castVlastName;
		this.castVid = castVid;
		this.castEpicNo = castEpicNo;
		this.castVadharNo = castVadharNo;
		this.castVpanNo = castVpanNo;
		this.castVsecurtiyQues = castVsecurtiyQues;
		this.castVsecurityAnsw = castVsecurityAnsw;
		this.castVpassword = castVpassword;
		this.castVotingCountry = castVotingCountry;
		this.castVotingState = castVotingState;
		this.castVotingCity = castVotingCity;
		this.castVotingTown = castVotingTown;
		this.castVotingPincode = castVotingPincode;
		this.castVotingPartyName = castVotingPartyName;
		this.castCanId = castCanId;
		this.castCanName = castCanName;
		this.castCanSymbol = castCanSymbol;
		this.castVoteTime = castVoteTime;
		this.castVotingStatus = castVotingStatus;
		this.voterregistrations = voterregistrations;
		this.resultprocesses = resultprocesses;
	}

	public Integer getCastId() {
		return this.castId;
	}

	public void setCastId(Integer castId) {
		this.castId = castId;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Candidateregistration getCandidateregistration() {
		return this.candidateregistration;
	}

	public void setCandidateregistration(Candidateregistration candidateregistration) {
		this.candidateregistration = candidateregistration;
	}

	public Party getParty() {
		return this.party;
	}

	public void setParty(Party party) {
		this.party = party;
	}

	public String getCastVfirstName() {
		return this.castVfirstName;
	}

	public void setCastVfirstName(String castVfirstName) {
		this.castVfirstName = castVfirstName;
	}

	public String getCastVlastName() {
		return this.castVlastName;
	}

	public void setCastVlastName(String castVlastName) {
		this.castVlastName = castVlastName;
	}

	public Integer getCastVid() {
		return this.castVid;
	}

	public void setCastVid(Integer castVid) {
		this.castVid = castVid;
	}

	public String getCastEpicNo() {
		return this.castEpicNo;
	}

	public void setCastEpicNo(String castEpicNo) {
		this.castEpicNo = castEpicNo;
	}

	public String getCastVadharNo() {
		return this.castVadharNo;
	}

	public void setCastVadharNo(String castVadharNo) {
		this.castVadharNo = castVadharNo;
	}

	public String getCastVpanNo() {
		return this.castVpanNo;
	}

	public void setCastVpanNo(String castVpanNo) {
		this.castVpanNo = castVpanNo;
	}

	public String getCastVsecurtiyQues() {
		return this.castVsecurtiyQues;
	}

	public void setCastVsecurtiyQues(String castVsecurtiyQues) {
		this.castVsecurtiyQues = castVsecurtiyQues;
	}

	public String getCastVsecurityAnsw() {
		return this.castVsecurityAnsw;
	}

	public void setCastVsecurityAnsw(String castVsecurityAnsw) {
		this.castVsecurityAnsw = castVsecurityAnsw;
	}

	public String getCastVpassword() {
		return this.castVpassword;
	}

	public void setCastVpassword(String castVpassword) {
		this.castVpassword = castVpassword;
	}

	public String getCastVotingCountry() {
		return this.castVotingCountry;
	}

	public void setCastVotingCountry(String castVotingCountry) {
		this.castVotingCountry = castVotingCountry;
	}

	public String getCastVotingState() {
		return this.castVotingState;
	}

	public void setCastVotingState(String castVotingState) {
		this.castVotingState = castVotingState;
	}

	public String getCastVotingCity() {
		return this.castVotingCity;
	}

	public void setCastVotingCity(String castVotingCity) {
		this.castVotingCity = castVotingCity;
	}

	public String getCastVotingTown() {
		return this.castVotingTown;
	}

	public void setCastVotingTown(String castVotingTown) {
		this.castVotingTown = castVotingTown;
	}

	public String getCastVotingPincode() {
		return this.castVotingPincode;
	}

	public void setCastVotingPincode(String castVotingPincode) {
		this.castVotingPincode = castVotingPincode;
	}

	public String getCastVotingPartyName() {
		return this.castVotingPartyName;
	}

	public void setCastVotingPartyName(String castVotingPartyName) {
		this.castVotingPartyName = castVotingPartyName;
	}

	public Integer getCastCanId() {
		return this.castCanId;
	}

	public void setCastCanId(Integer castCanId) {
		this.castCanId = castCanId;
	}

	public String getCastCanName() {
		return this.castCanName;
	}

	public void setCastCanName(String castCanName) {
		this.castCanName = castCanName;
	}

	public byte[] getCastCanSymbol() {
		return this.castCanSymbol;
	}

	public void setCastCanSymbol(byte[] castCanSymbol) {
		this.castCanSymbol = castCanSymbol;
	}

	public Date getCastVoteTime() {
		return this.castVoteTime;
	}

	public void setCastVoteTime(Date castVoteTime) {
		this.castVoteTime = castVoteTime;
	}

	public String getCastVotingStatus() {
		return this.castVotingStatus;
	}

	public void setCastVotingStatus(String castVotingStatus) {
		this.castVotingStatus = castVotingStatus;
	}

	public Set getVoterregistrations() {
		return this.voterregistrations;
	}

	public void setVoterregistrations(Set voterregistrations) {
		this.voterregistrations = voterregistrations;
	}

	public Set getResultprocesses() {
		return this.resultprocesses;
	}

	public void setResultprocesses(Set resultprocesses) {
		this.resultprocesses = resultprocesses;
	}

}
