package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Cpi generated by hbm2java
 */
public class Cpi implements java.io.Serializable {

	private Integer cpiId;
	private String cpiName;
	private Integer cpiCandidateRegId;
	private Integer cpiTotalVotes;
	private Integer cpiStateTotalVotes;
	private Integer cpiCityTotalVotes;
	private Integer cpiAreaTotalVotes;
	private Integer cpiFemaleTotalVotes;
	private Integer cpiMaleTotalVotes;

	public Cpi() {
	}

	public Cpi(String cpiName, Integer cpiCandidateRegId, Integer cpiTotalVotes, Integer cpiStateTotalVotes,
			Integer cpiCityTotalVotes, Integer cpiAreaTotalVotes, Integer cpiFemaleTotalVotes, Integer cpiMaleTotalVotes) {
		this.cpiName = cpiName;
		this.cpiCandidateRegId = cpiCandidateRegId;
		this.cpiTotalVotes = cpiTotalVotes;
		this.cpiStateTotalVotes = cpiStateTotalVotes;
		this.cpiCityTotalVotes = cpiCityTotalVotes;
		this.cpiAreaTotalVotes = cpiAreaTotalVotes;
		this.cpiFemaleTotalVotes = cpiFemaleTotalVotes;
		this.cpiMaleTotalVotes = cpiMaleTotalVotes;
	}

	public Integer getCpiId() {
		return this.cpiId;
	}

	public void setCpiId(Integer cpiId) {
		this.cpiId = cpiId;
	}

	public String getCpiName() {
		return this.cpiName;
	}

	public void setCpiName(String cpiName) {
		this.cpiName = cpiName;
	}

	public Integer getCpiCandidateRegId() {
		return this.cpiCandidateRegId;
	}

	public void setCpiCandidateRegId(Integer cpiCandidateRegId) {
		this.cpiCandidateRegId = cpiCandidateRegId;
	}

	public Integer getCpiTotalVotes() {
		return this.cpiTotalVotes;
	}

	public void setCpiTotalVotes(Integer cpiTotalVotes) {
		this.cpiTotalVotes = cpiTotalVotes;
	}

	public Integer getCpiStateTotalVotes() {
		return this.cpiStateTotalVotes;
	}

	public void setCpiStateTotalVotes(Integer cpiStateTotalVotes) {
		this.cpiStateTotalVotes = cpiStateTotalVotes;
	}

	public Integer getCpiCityTotalVotes() {
		return this.cpiCityTotalVotes;
	}

	public void setCpiCityTotalVotes(Integer cpiCityTotalVotes) {
		this.cpiCityTotalVotes = cpiCityTotalVotes;
	}

	public Integer getCpiAreaTotalVotes() {
		return this.cpiAreaTotalVotes;
	}

	public void setCpiAreaTotalVotes(Integer cpiAreaTotalVotes) {
		this.cpiAreaTotalVotes = cpiAreaTotalVotes;
	}

	public Integer getCpiFemaleTotalVotes() {
		return this.cpiFemaleTotalVotes;
	}

	public void setCpiFemaleTotalVotes(Integer cpiFemaleTotalVotes) {
		this.cpiFemaleTotalVotes = cpiFemaleTotalVotes;
	}

	public Integer getCpiMaleTotalVotes() {
		return this.cpiMaleTotalVotes;
	}

	public void setCpiMaleTotalVotes(Integer cpiMaleTotalVotes) {
		this.cpiMaleTotalVotes = cpiMaleTotalVotes;
	}

}
