package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Incp generated by hbm2java
 */
public class Incp implements java.io.Serializable {

	private Integer incpId;
	private String incpName;
	private Integer incpCandidateRegId;
	private Integer incpTotalVotes;
	private Integer incpStateTotalVotes;
	private Integer incpCityTotalVotes;
	private Integer incpAreaTotalVotes;
	private Integer incpFemaleTotalVotes;
	private Integer incpMaleTotalVotes;

	public Incp() {
	}

	public Incp(String incpName, Integer incpCandidateRegId, Integer incpTotalVotes, Integer incpStateTotalVotes,
			Integer incpCityTotalVotes, Integer incpAreaTotalVotes, Integer incpFemaleTotalVotes,
			Integer incpMaleTotalVotes) {
		this.incpName = incpName;
		this.incpCandidateRegId = incpCandidateRegId;
		this.incpTotalVotes = incpTotalVotes;
		this.incpStateTotalVotes = incpStateTotalVotes;
		this.incpCityTotalVotes = incpCityTotalVotes;
		this.incpAreaTotalVotes = incpAreaTotalVotes;
		this.incpFemaleTotalVotes = incpFemaleTotalVotes;
		this.incpMaleTotalVotes = incpMaleTotalVotes;
	}

	public Integer getIncpId() {
		return this.incpId;
	}

	public void setIncpId(Integer incpId) {
		this.incpId = incpId;
	}

	public String getIncpName() {
		return this.incpName;
	}

	public void setIncpName(String incpName) {
		this.incpName = incpName;
	}

	public Integer getIncpCandidateRegId() {
		return this.incpCandidateRegId;
	}

	public void setIncpCandidateRegId(Integer incpCandidateRegId) {
		this.incpCandidateRegId = incpCandidateRegId;
	}

	public Integer getIncpTotalVotes() {
		return this.incpTotalVotes;
	}

	public void setIncpTotalVotes(Integer incpTotalVotes) {
		this.incpTotalVotes = incpTotalVotes;
	}

	public Integer getIncpStateTotalVotes() {
		return this.incpStateTotalVotes;
	}

	public void setIncpStateTotalVotes(Integer incpStateTotalVotes) {
		this.incpStateTotalVotes = incpStateTotalVotes;
	}

	public Integer getIncpCityTotalVotes() {
		return this.incpCityTotalVotes;
	}

	public void setIncpCityTotalVotes(Integer incpCityTotalVotes) {
		this.incpCityTotalVotes = incpCityTotalVotes;
	}

	public Integer getIncpAreaTotalVotes() {
		return this.incpAreaTotalVotes;
	}

	public void setIncpAreaTotalVotes(Integer incpAreaTotalVotes) {
		this.incpAreaTotalVotes = incpAreaTotalVotes;
	}

	public Integer getIncpFemaleTotalVotes() {
		return this.incpFemaleTotalVotes;
	}

	public void setIncpFemaleTotalVotes(Integer incpFemaleTotalVotes) {
		this.incpFemaleTotalVotes = incpFemaleTotalVotes;
	}

	public Integer getIncpMaleTotalVotes() {
		return this.incpMaleTotalVotes;
	}

	public void setIncpMaleTotalVotes(Integer incpMaleTotalVotes) {
		this.incpMaleTotalVotes = incpMaleTotalVotes;
	}

}
