package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

/**
 * Ncp generated by hbm2java
 */
public class Ncp implements java.io.Serializable {

	private Integer ncpId;
	private String ncpName;
	private Integer ncpCandidateRegId;
	private Integer ncpTotalVotes;
	private Integer ncpStateTotalVotes;
	private Integer ncpCityTotalVotes;
	private Integer ncpAreaTotalVotes;
	private Integer ncpFemaleTotalVotes;
	private Integer ncpMaleTotalVotes;

	public Ncp() {
	}

	public Ncp(String ncpName, Integer ncpCandidateRegId, Integer ncpTotalVotes, Integer ncpStateTotalVotes,
			Integer ncpCityTotalVotes, Integer ncpAreaTotalVotes, Integer ncpFemaleTotalVotes, Integer ncpMaleTotalVotes) {
		this.ncpName = ncpName;
		this.ncpCandidateRegId = ncpCandidateRegId;
		this.ncpTotalVotes = ncpTotalVotes;
		this.ncpStateTotalVotes = ncpStateTotalVotes;
		this.ncpCityTotalVotes = ncpCityTotalVotes;
		this.ncpAreaTotalVotes = ncpAreaTotalVotes;
		this.ncpFemaleTotalVotes = ncpFemaleTotalVotes;
		this.ncpMaleTotalVotes = ncpMaleTotalVotes;
	}

	public Integer getNcpId() {
		return this.ncpId;
	}

	public void setNcpId(Integer ncpId) {
		this.ncpId = ncpId;
	}

	public String getNcpName() {
		return this.ncpName;
	}

	public void setNcpName(String ncpName) {
		this.ncpName = ncpName;
	}

	public Integer getNcpCandidateRegId() {
		return this.ncpCandidateRegId;
	}

	public void setNcpCandidateRegId(Integer ncpCandidateRegId) {
		this.ncpCandidateRegId = ncpCandidateRegId;
	}

	public Integer getNcpTotalVotes() {
		return this.ncpTotalVotes;
	}

	public void setNcpTotalVotes(Integer ncpTotalVotes) {
		this.ncpTotalVotes = ncpTotalVotes;
	}

	public Integer getNcpStateTotalVotes() {
		return this.ncpStateTotalVotes;
	}

	public void setNcpStateTotalVotes(Integer ncpStateTotalVotes) {
		this.ncpStateTotalVotes = ncpStateTotalVotes;
	}

	public Integer getNcpCityTotalVotes() {
		return this.ncpCityTotalVotes;
	}

	public void setNcpCityTotalVotes(Integer ncpCityTotalVotes) {
		this.ncpCityTotalVotes = ncpCityTotalVotes;
	}

	public Integer getNcpAreaTotalVotes() {
		return this.ncpAreaTotalVotes;
	}

	public void setNcpAreaTotalVotes(Integer ncpAreaTotalVotes) {
		this.ncpAreaTotalVotes = ncpAreaTotalVotes;
	}

	public Integer getNcpFemaleTotalVotes() {
		return this.ncpFemaleTotalVotes;
	}

	public void setNcpFemaleTotalVotes(Integer ncpFemaleTotalVotes) {
		this.ncpFemaleTotalVotes = ncpFemaleTotalVotes;
	}

	public Integer getNcpMaleTotalVotes() {
		return this.ncpMaleTotalVotes;
	}

	public void setNcpMaleTotalVotes(Integer ncpMaleTotalVotes) {
		this.ncpMaleTotalVotes = ncpMaleTotalVotes;
	}

}
