package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Party generated by hbm2java
 */
public class Party implements java.io.Serializable {

	private Integer partyId;
	private String partyName;
	private String partSymbol;
	private Integer partyCanRegId;
	private Integer bjpTotalVotes;
	private Integer bjpStateTotalVotes;
	private Integer bjpCityTotalVotes;
	private Integer bjpAreaTotalVotes;
	private Integer bjpFemaleTotalVotes;
	private Integer bjpMaleTotalVotes;
	private Set castvotes = new HashSet(0);
	private Set candidateregistrations = new HashSet(0);

	public Party() {
	}

	public Party(String partyName, String partSymbol, Integer partyCanRegId, Integer bjpTotalVotes,
			Integer bjpStateTotalVotes, Integer bjpCityTotalVotes, Integer bjpAreaTotalVotes,
			Integer bjpFemaleTotalVotes, Integer bjpMaleTotalVotes, Set castvotes, Set candidateregistrations) {
		this.partyName = partyName;
		this.partSymbol = partSymbol;
		this.partyCanRegId = partyCanRegId;
		this.bjpTotalVotes = bjpTotalVotes;
		this.bjpStateTotalVotes = bjpStateTotalVotes;
		this.bjpCityTotalVotes = bjpCityTotalVotes;
		this.bjpAreaTotalVotes = bjpAreaTotalVotes;
		this.bjpFemaleTotalVotes = bjpFemaleTotalVotes;
		this.bjpMaleTotalVotes = bjpMaleTotalVotes;
		this.castvotes = castvotes;
		this.candidateregistrations = candidateregistrations;
	}

	public Integer getPartyId() {
		return this.partyId;
	}

	public void setPartyId(Integer partyId) {
		this.partyId = partyId;
	}

	public String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}

	public String getPartSymbol() {
		return this.partSymbol;
	}

	public void setPartSymbol(String partSymbol) {
		this.partSymbol = partSymbol;
	}

	public Integer getPartyCanRegId() {
		return this.partyCanRegId;
	}

	public void setPartyCanRegId(Integer partyCanRegId) {
		this.partyCanRegId = partyCanRegId;
	}

	public Integer getBjpTotalVotes() {
		return this.bjpTotalVotes;
	}

	public void setBjpTotalVotes(Integer bjpTotalVotes) {
		this.bjpTotalVotes = bjpTotalVotes;
	}

	public Integer getBjpStateTotalVotes() {
		return this.bjpStateTotalVotes;
	}

	public void setBjpStateTotalVotes(Integer bjpStateTotalVotes) {
		this.bjpStateTotalVotes = bjpStateTotalVotes;
	}

	public Integer getBjpCityTotalVotes() {
		return this.bjpCityTotalVotes;
	}

	public void setBjpCityTotalVotes(Integer bjpCityTotalVotes) {
		this.bjpCityTotalVotes = bjpCityTotalVotes;
	}

	public Integer getBjpAreaTotalVotes() {
		return this.bjpAreaTotalVotes;
	}

	public void setBjpAreaTotalVotes(Integer bjpAreaTotalVotes) {
		this.bjpAreaTotalVotes = bjpAreaTotalVotes;
	}

	public Integer getBjpFemaleTotalVotes() {
		return this.bjpFemaleTotalVotes;
	}

	public void setBjpFemaleTotalVotes(Integer bjpFemaleTotalVotes) {
		this.bjpFemaleTotalVotes = bjpFemaleTotalVotes;
	}

	public Integer getBjpMaleTotalVotes() {
		return this.bjpMaleTotalVotes;
	}

	public void setBjpMaleTotalVotes(Integer bjpMaleTotalVotes) {
		this.bjpMaleTotalVotes = bjpMaleTotalVotes;
	}

	public Set getCastvotes() {
		return this.castvotes;
	}

	public void setCastvotes(Set castvotes) {
		this.castvotes = castvotes;
	}

	public Set getCandidateregistrations() {
		return this.candidateregistrations;
	}

	public void setCandidateregistrations(Set candidateregistrations) {
		this.candidateregistrations = candidateregistrations;
	}

}
