package com.pojo;

// Generated 27 Apr, 2017 2:38:11 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Voterregistration generated by hbm2java
 */
public class Voterregistration implements java.io.Serializable {

	private Integer vid;
	private Admin admin;
	private Castvote castvote;
	private String vfirstname;
	private String vmiddlename;
	private String vlastname;
	private String vgender;
	private String vmaritalstatus;
	private String vfathername;
	private String vmothername;
	private String vwifename;
	private String vhusbandname;
	private String vgaurdianname;
	private String vpermacountry;
	private String vpermastate;
	private String vpermacity;
	private String vpermatown;
	private String vpermaaddress;
	private String vpermapincode;
	private String vcorrescountry;
	private String vcorresstate;
	private String vcorrescity;
	private String vcorrestown;
	private String vcorresaddress;
	private String vcorrespincode;
	private String voccupatiostatus;
	private byte[] voccupationdoc;
	private String vdesignation;
	private Integer vage;
	private Date vdob;
	private String vadharno;
	private byte[] vadhardoc;
	private String vpanno;
	private byte[] vpandoc;
	private String vphoto;
	private String vmob;
	private Integer vaddressId;
	private Boolean vpwdstatus;
	private String vpwdudidno;
	private byte[] vpwddoc;
	private String vemailId;
	private String vpassword;
	private String vrepassword;
	private String vsecurityQues;
	private String vsecurityAnswer;
	private String vcancelRegistration;
	private String vcancelOtherDetails;
	private byte[] vcancelRegistrationDoc;
	private String vepicNo;
	private String vstatus1;
	private String vstatus2;
	private String vstatus3;
	private Set addresses = new HashSet(0);

	public Voterregistration() {
	}

	public Voterregistration(Admin admin, Castvote castvote, String vfirstname, String vmiddlename, String vlastname,
			String vgender, String vmaritalstatus, String vfathername, String vmothername, String vwifename,
			String vhusbandname, String vgaurdianname, String vpermacountry, String vpermastate, String vpermacity,
			String vpermatown, String vpermaaddress, String vpermapincode, String vcorrescountry, String vcorresstate,
			String vcorrescity, String vcorrestown, String vcorresaddress, String vcorrespincode,
			String voccupatiostatus, byte[] voccupationdoc, String vdesignation, Integer vage, Date vdob,
			String vadharno, byte[] vadhardoc, String vpanno, byte[] vpandoc, String vphoto, String vmob,
			Integer vaddressId, Boolean vpwdstatus, String vpwdudidno, byte[] vpwddoc, String vemailId,
			String vpassword, String vrepassword, String vsecurityQues, String vsecurityAnswer,
			String vcancelRegistration, String vcancelOtherDetails, byte[] vcancelRegistrationDoc, String vepicNo,
			String vstatus1, String vstatus2, String vstatus3, Set addresses) {
		this.admin = admin;
		this.castvote = castvote;
		this.vfirstname = vfirstname;
		this.vmiddlename = vmiddlename;
		this.vlastname = vlastname;
		this.vgender = vgender;
		this.vmaritalstatus = vmaritalstatus;
		this.vfathername = vfathername;
		this.vmothername = vmothername;
		this.vwifename = vwifename;
		this.vhusbandname = vhusbandname;
		this.vgaurdianname = vgaurdianname;
		this.vpermacountry = vpermacountry;
		this.vpermastate = vpermastate;
		this.vpermacity = vpermacity;
		this.vpermatown = vpermatown;
		this.vpermaaddress = vpermaaddress;
		this.vpermapincode = vpermapincode;
		this.vcorrescountry = vcorrescountry;
		this.vcorresstate = vcorresstate;
		this.vcorrescity = vcorrescity;
		this.vcorrestown = vcorrestown;
		this.vcorresaddress = vcorresaddress;
		this.vcorrespincode = vcorrespincode;
		this.voccupatiostatus = voccupatiostatus;
		this.voccupationdoc = voccupationdoc;
		this.vdesignation = vdesignation;
		this.vage = vage;
		this.vdob = vdob;
		this.vadharno = vadharno;
		this.vadhardoc = vadhardoc;
		this.vpanno = vpanno;
		this.vpandoc = vpandoc;
		this.vphoto = vphoto;
		this.vmob = vmob;
		this.vaddressId = vaddressId;
		this.vpwdstatus = vpwdstatus;
		this.vpwdudidno = vpwdudidno;
		this.vpwddoc = vpwddoc;
		this.vemailId = vemailId;
		this.vpassword = vpassword;
		this.vrepassword = vrepassword;
		this.vsecurityQues = vsecurityQues;
		this.vsecurityAnswer = vsecurityAnswer;
		this.vcancelRegistration = vcancelRegistration;
		this.vcancelOtherDetails = vcancelOtherDetails;
		this.vcancelRegistrationDoc = vcancelRegistrationDoc;
		this.vepicNo = vepicNo;
		this.vstatus1 = vstatus1;
		this.vstatus2 = vstatus2;
		this.vstatus3 = vstatus3;
		this.addresses = addresses;
	}

	public Integer getVid() {
		return this.vid;
	}

	public void setVid(Integer vid) {
		this.vid = vid;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Castvote getCastvote() {
		return this.castvote;
	}

	public void setCastvote(Castvote castvote) {
		this.castvote = castvote;
	}

	public String getVfirstname() {
		return this.vfirstname;
	}

	public void setVfirstname(String vfirstname) {
		this.vfirstname = vfirstname;
	}

	public String getVmiddlename() {
		return this.vmiddlename;
	}

	public void setVmiddlename(String vmiddlename) {
		this.vmiddlename = vmiddlename;
	}

	public String getVlastname() {
		return this.vlastname;
	}

	public void setVlastname(String vlastname) {
		this.vlastname = vlastname;
	}

	public String getVgender() {
		return this.vgender;
	}

	public void setVgender(String vgender) {
		this.vgender = vgender;
	}

	public String getVmaritalstatus() {
		return this.vmaritalstatus;
	}

	public void setVmaritalstatus(String vmaritalstatus) {
		this.vmaritalstatus = vmaritalstatus;
	}

	public String getVfathername() {
		return this.vfathername;
	}

	public void setVfathername(String vfathername) {
		this.vfathername = vfathername;
	}

	public String getVmothername() {
		return this.vmothername;
	}

	public void setVmothername(String vmothername) {
		this.vmothername = vmothername;
	}

	public String getVwifename() {
		return this.vwifename;
	}

	public void setVwifename(String vwifename) {
		this.vwifename = vwifename;
	}

	public String getVhusbandname() {
		return this.vhusbandname;
	}

	public void setVhusbandname(String vhusbandname) {
		this.vhusbandname = vhusbandname;
	}

	public String getVgaurdianname() {
		return this.vgaurdianname;
	}

	public void setVgaurdianname(String vgaurdianname) {
		this.vgaurdianname = vgaurdianname;
	}

	public String getVpermacountry() {
		return this.vpermacountry;
	}

	public void setVpermacountry(String vpermacountry) {
		this.vpermacountry = vpermacountry;
	}

	public String getVpermastate() {
		return this.vpermastate;
	}

	public void setVpermastate(String vpermastate) {
		this.vpermastate = vpermastate;
	}

	public String getVpermacity() {
		return this.vpermacity;
	}

	public void setVpermacity(String vpermacity) {
		this.vpermacity = vpermacity;
	}

	public String getVpermatown() {
		return this.vpermatown;
	}

	public void setVpermatown(String vpermatown) {
		this.vpermatown = vpermatown;
	}

	public String getVpermaaddress() {
		return this.vpermaaddress;
	}

	public void setVpermaaddress(String vpermaaddress) {
		this.vpermaaddress = vpermaaddress;
	}

	public String getVpermapincode() {
		return this.vpermapincode;
	}

	public void setVpermapincode(String vpermapincode) {
		this.vpermapincode = vpermapincode;
	}

	public String getVcorrescountry() {
		return this.vcorrescountry;
	}

	public void setVcorrescountry(String vcorrescountry) {
		this.vcorrescountry = vcorrescountry;
	}

	public String getVcorresstate() {
		return this.vcorresstate;
	}

	public void setVcorresstate(String vcorresstate) {
		this.vcorresstate = vcorresstate;
	}

	public String getVcorrescity() {
		return this.vcorrescity;
	}

	public void setVcorrescity(String vcorrescity) {
		this.vcorrescity = vcorrescity;
	}

	public String getVcorrestown() {
		return this.vcorrestown;
	}

	public void setVcorrestown(String vcorrestown) {
		this.vcorrestown = vcorrestown;
	}

	public String getVcorresaddress() {
		return this.vcorresaddress;
	}

	public void setVcorresaddress(String vcorresaddress) {
		this.vcorresaddress = vcorresaddress;
	}

	public String getVcorrespincode() {
		return this.vcorrespincode;
	}

	public void setVcorrespincode(String vcorrespincode) {
		this.vcorrespincode = vcorrespincode;
	}

	public String getVoccupatiostatus() {
		return this.voccupatiostatus;
	}

	public void setVoccupatiostatus(String voccupatiostatus) {
		this.voccupatiostatus = voccupatiostatus;
	}

	public byte[] getVoccupationdoc() {
		return this.voccupationdoc;
	}

	public void setVoccupationdoc(byte[] voccupationdoc) {
		this.voccupationdoc = voccupationdoc;
	}

	public String getVdesignation() {
		return this.vdesignation;
	}

	public void setVdesignation(String vdesignation) {
		this.vdesignation = vdesignation;
	}

	public Integer getVage() {
		return this.vage;
	}

	public void setVage(Integer vage) {
		this.vage = vage;
	}

	public Date getVdob() {
		return this.vdob;
	}

	public void setVdob(Date vdob) {
		this.vdob = vdob;
	}

	public String getVadharno() {
		return this.vadharno;
	}

	public void setVadharno(String vadharno) {
		this.vadharno = vadharno;
	}

	public byte[] getVadhardoc() {
		return this.vadhardoc;
	}

	public void setVadhardoc(byte[] vadhardoc) {
		this.vadhardoc = vadhardoc;
	}

	public String getVpanno() {
		return this.vpanno;
	}

	public void setVpanno(String vpanno) {
		this.vpanno = vpanno;
	}

	public byte[] getVpandoc() {
		return this.vpandoc;
	}

	public void setVpandoc(byte[] vpandoc) {
		this.vpandoc = vpandoc;
	}

	public String getVphoto() {
		return this.vphoto;
	}

	public void setVphoto(String vphoto) {
		this.vphoto = vphoto;
	}

	public String getVmob() {
		return this.vmob;
	}

	public void setVmob(String vmob) {
		this.vmob = vmob;
	}

	public Integer getVaddressId() {
		return this.vaddressId;
	}

	public void setVaddressId(Integer vaddressId) {
		this.vaddressId = vaddressId;
	}

	public Boolean getVpwdstatus() {
		return this.vpwdstatus;
	}

	public void setVpwdstatus(Boolean vpwdstatus) {
		this.vpwdstatus = vpwdstatus;
	}

	public String getVpwdudidno() {
		return this.vpwdudidno;
	}

	public void setVpwdudidno(String vpwdudidno) {
		this.vpwdudidno = vpwdudidno;
	}

	public byte[] getVpwddoc() {
		return this.vpwddoc;
	}

	public void setVpwddoc(byte[] vpwddoc) {
		this.vpwddoc = vpwddoc;
	}

	public String getVemailId() {
		return this.vemailId;
	}

	public void setVemailId(String vemailId) {
		this.vemailId = vemailId;
	}

	public String getVpassword() {
		return this.vpassword;
	}

	public void setVpassword(String vpassword) {
		this.vpassword = vpassword;
	}

	public String getVrepassword() {
		return this.vrepassword;
	}

	public void setVrepassword(String vrepassword) {
		this.vrepassword = vrepassword;
	}

	public String getVsecurityQues() {
		return this.vsecurityQues;
	}

	public void setVsecurityQues(String vsecurityQues) {
		this.vsecurityQues = vsecurityQues;
	}

	public String getVsecurityAnswer() {
		return this.vsecurityAnswer;
	}

	public void setVsecurityAnswer(String vsecurityAnswer) {
		this.vsecurityAnswer = vsecurityAnswer;
	}

	public String getVcancelRegistration() {
		return this.vcancelRegistration;
	}

	public void setVcancelRegistration(String vcancelRegistration) {
		this.vcancelRegistration = vcancelRegistration;
	}

	public String getVcancelOtherDetails() {
		return this.vcancelOtherDetails;
	}

	public void setVcancelOtherDetails(String vcancelOtherDetails) {
		this.vcancelOtherDetails = vcancelOtherDetails;
	}

	public byte[] getVcancelRegistrationDoc() {
		return this.vcancelRegistrationDoc;
	}

	public void setVcancelRegistrationDoc(byte[] vcancelRegistrationDoc) {
		this.vcancelRegistrationDoc = vcancelRegistrationDoc;
	}

	public String getVepicNo() {
		return this.vepicNo;
	}

	public void setVepicNo(String vepicNo) {
		this.vepicNo = vepicNo;
	}

	public String getVstatus1() {
		return this.vstatus1;
	}

	public void setVstatus1(String vstatus1) {
		this.vstatus1 = vstatus1;
	}

	public String getVstatus2() {
		return this.vstatus2;
	}

	public void setVstatus2(String vstatus2) {
		this.vstatus2 = vstatus2;
	}

	public String getVstatus3() {
		return this.vstatus3;
	}

	public void setVstatus3(String vstatus3) {
		this.vstatus3 = vstatus3;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

}
